
services:
  app:
    build: .
    container_name: ai_text_gen
    ports:
      - "5000:5000"

    depends_on:
      - db
    
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  test:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase_test
    volumes:
      - .:/app
    entrypoint: ["pytest"]
volumes:
  pgdata: